version: '2'
services:
  kafka.console:
    image: kafka.console/service:latest
    ports:
     - "8080:8080"
    depends_on:
     - kafka
  kafka:
    image: ches/kafka:0.8.2.2
    expose:
      - "9092"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      - ZOOKEEPER_CONNECTION_STRING=192.168.99.100
    depends_on:
     - zookeeper
  zookeeper:
    image: jplock/zookeeper:3.4.6
    expose:
      - "2181"
    ports:
      - "2181:2181"
